import type { Biccame } from '@/types/biccame';
import { REGION } from '@/types/biccame';

const modelVersion = 5;

const models: Biccame[] = [
  {
    name: '京都たん',
    storeName: 'ビックカメラ JR京都駅店',
    url: 'kyoto',
    pos: {
      lat: 34.985873,
      lng: 135.755638,
    },
    visitable: false,
    region: REGION.misc,
  },
  {
    name: '新横たん',
    storeName: 'ビックカメラ 新横浜店',
    url: 'shinyoko',
    pos: {
      lat: 35.5078187,
      lng: 139.6174651,
    },
    visitable: true,
    region: REGION.tokyo,
  },
  {
    name: 'みっけたん',
    storeName: 'ビックカメラ 赤坂見附駅店',
    url: 'akasaka',
    pos: {
      lat: 35.6771006,
      lng: 139.7367753,
    },
    visitable: true,
    region: REGION.tokyo,
  },
  {
    name: '横西たん',
    storeName: 'ビックカメラ 横浜西口店',
    url: 'yokonishi',
    pos: {
      lat: 35.4643568,
      lng: 139.6163515,
    },
    visitable: true,
    region: REGION.tokyo,
  },
  {
    name: 'にいがたたん',
    storeName: 'ビックカメラ 新潟店',
    url: 'niigata',
    pos: {
      lat: 37.9119782,
      lng: 139.0632138,
    },
    visitable: true,
    region: REGION.misc,
  },
  {
    name: 'くまもとたん',
    storeName: 'ビックカメラ アミュプラザくまもと店',
    url: 'kumamoto',
    pos: {
      lat: 32.7903644,
      lng: 130.689272,
    },
    visitable: true,
    region: REGION.misc,
  },
  {
    name: '藤沢たん',
    storeName: 'ビックカメラ 藤沢店',
    url: 'fujisawa',
    pos: {
      lat: 35.3395487,
      lng: 139.4882252,
    },
    visitable: true,
    region: REGION.tokyo,
  },
  {
    name: 'なんばたん',
    storeName: 'ビックカメラ なんば店',
    url: 'nanba',
    pos: {
      lat: 34.6666726,
      lng: 135.5025827,
    },
    visitable: true,
    region: REGION.osaka,
  },
  {
    name: '町田たん',
    storeName: 'ビックカメラ 町田店',
    url: 'machida',
    pos: {
      lat: 35.5439831,
      lng: 139.445084,
    },
    visitable: false,
    region: REGION.tokyo,
  },
  {
    name: 'あいタワたん',
    storeName: 'ビックカメラ池袋西口 IT tower店',
    url: 'ittower',
    pos: {
      lat: 35.7312935,
      lng: 139.705081,
    },
    visitable: true,
    region: REGION.tokyo,
  },
  {
    name: 'たかさきたん',
    storeName: 'ビックカメラ 高崎東口店',
    url: 'takasaki',
    pos: {
      lat: 36.3217422,
      lng: 139.0142643,
    },
    visitable: true,
    region: REGION.tokyo,
  },
  {
    name: 'なごやげーとたん',
    storeName: 'ビックカメラ 名古屋 JRゲートタワー店',
    url: 'nagoyagate',
    pos: {
      lat: 35.1722393,
      lng: 136.8823772,
    },
    visitable: true,
    region: REGION.misc,
  },
  {
    name: 'なごやたん',
    storeName: 'ビックカメラ 名古屋駅西店',
    url: 'nagoya',
    pos: {
      lat: 35.1702659,
      lng: 136.8795872,
    },
    visitable: true,
    region: REGION.misc,
  },
  {
    name: '水戸たん',
    storeName: 'ビックカメラ 水戸駅店',
    url: 'mito',
    pos: {
      lat: 36.3701475,
      lng: 140.4768006,
    },
    visitable: true,
    region: REGION.tokyo,
  },
  {
    name: '池西たん',
    storeName: 'ビックカメラ 池袋西口店',
    url: 'ikenishi',
    pos: {
      lat: 35.7307684,
      lng: 139.7088983,
    },
    visitable: true,
    region: REGION.tokyo,
  },
  {
    name: '有楽町たん',
    storeName: 'ビックカメラ 有楽町店',
    url: 'yuurakuchou',
    pos: {
      lat: 35.6753814,
      lng: 139.7629088,
    },
    visitable: true,
    region: REGION.tokyo,
  },
  {
    name: '八王子たん',
    storeName: 'ビックカメラ JR八王子駅店',
    url: 'hachioji',
    pos: {
      lat: 35.654573,
      lng: 139.338804,
    },
    visitable: true,
    region: REGION.tokyo,
  },
  {
    name: '柏たん',
    storeName: 'ビックカメラ 柏店',
    url: 'kashiwa',
    pos: {
      lat: 35.8623381,
      lng: 139.9721465,
    },
    visitable: true,
    region: REGION.tokyo,
  },
  {
    name: 'ふなたん',
    storeName: 'ビックカメラ 船橋駅FACE店',
    url: 'funabashi',
    pos: {
      lat: 35.7008719,
      lng: 139.9855232,
    },
    visitable: true,
    region: REGION.tokyo,
  },
  {
    name: 'しんじゅくたん(ビックロたん)',
    storeName: 'ビックカメラ 新宿東口店',
    url: 'bicqlo',
    pos: {
      lat: 35.6913041,
      lng: 139.7029741,
    },
    visitable: true,
    region: REGION.tokyo,
  },
  {
    name: 'はまたん',
    storeName: 'ビックカメラ 浜松店',
    url: 'hamamatsu',
    pos: {
      lat: 34.7034222,
      lng: 137.7338944,
    },
    visitable: true,
    region: REGION.misc,
  },
  {
    name: '新宿西口たん',
    storeName: 'ビックカメラ 新宿西口店',
    url: 'shinjyuku',
    pos: {
      lat: 35.6925129,
      lng: 139.6985563,
    },
    visitable: true,
    region: REGION.tokyo,
  },
  {
    name: 'アキバたん',
    storeName: 'ビックカメラ AKIBA',
    url: 'akiba',
    pos: {
      lat: 35.699826,
      lng: 139.7717547,
    },
    visitable: true,
    region: REGION.tokyo,
  },
  {
    name: 'フォトたん',
    storeName: 'BIC PHOTO',
    url: 'photo',
    pos: {
      lat: 35.7299324,
      lng: 139.7132993,
    },
    visitable: false,
    region: REGION.tokyo,
  },
  {
    name: 'カメ館たん',
    storeName: 'ビックカメラ 池袋東口カメラ館',
    url: 'camera',
    pos: {
      lat: 35.7299324,
      lng: 139.7132993,
    },
    visitable: false,
    region: REGION.tokyo,
  },
  {
    name: 'パソ館たん',
    storeName: 'ビックカメラ 池袋本店パソコン館',
    url: 'pkan',
    pos: {
      lat: 35.731563,
      lng: 139.7135962,
    },
    visitable: true,
    region: REGION.tokyo,
  },
  {
    name: 'しぶとーたん',
    storeName: 'ビックカメラ 渋谷東口店',
    url: 'shibuto',
    pos: {
      lat: 35.6599174,
      lng: 139.7020684,
    },
    visitable: true,
    region: REGION.tokyo,
  },
  {
    name: 'しぶハチたん',
    storeName: 'ビックカメラ 渋谷ハチ公口店',
    url: 'shibuhachi',
    pos: {
      lat: 35.6593429,
      lng: 139.6994798,
    },
    visitable: true,
    region: REGION.tokyo,
  },
  {
    name: 'さがみたん',
    storeName: 'ビックカメラ 相模大野駅店',
    url: 'sagami',
    pos: {
      lat: 35.5314686,
      lng: 139.4374261,
    },
    visitable: true,
    region: REGION.tokyo,
  },
  {
    name: 'さっぽろたん',
    storeName: 'ビックカメラ 札幌店',
    url: 'sapporo',
    pos: {
      lat: 43.0665413,
      lng: 141.3527927,
    },
    visitable: true,
    region: REGION.misc,
  },
  {
    name: '広島たん',
    storeName: 'ビックカメラ 広島駅前店',
    url: 'hiroshima',
    pos: {
      lat: 34.3959004,
      lng: 132.4750648,
    },
    visitable: true,
    region: REGION.misc,
  },
  {
    name: 'せいせきたん',
    storeName: 'ビックカメラ 聖蹟桜ヶ丘駅店',
    url: 'seiseki',
    pos: {
      lat: 35.6505265,
      lng: 139.4473744,
    },
    visitable: false,
    region: REGION.tokyo,
  },
  {
    name: 'あべのたん',
    storeName: 'ビックカメラ あべの キューズモール店',
    url: 'abeno',
    pos: {
      lat: 34.6439369,
      lng: 135.5115851,
    },
    visitable: true,
    region: REGION.osaka,
  },
  {
    name: '調布たん',
    storeName: 'ビックカメラ 京王調布店',
    url: 'chofu',
    pos: {
      lat: 35.6522598,
      lng: 139.5430908,
    },
    visitable: true,
    region: REGION.tokyo,
  },
  {
    name: '岡山たん',
    storeName: 'ビックカメラ 岡山駅前店',
    url: 'okayama',
    pos: {
      lat: 34.6658681,
      lng: 133.9198701,
    },
    visitable: true,
    region: REGION.misc,
  },
  {
    name: 'たかつきたん',
    storeName: 'ビックカメラ 高槻阪急スクエア店',
    url: 'takatsuki',
    pos: {
      lat: 34.8538771,
      lng: 135.6183241,
    },
    visitable: true,
    region: REGION.osaka,
  },
  {
    name: '新東たん',
    storeName: 'ビックカメラ 新宿東口駅前店',
    url: 'shintou',
    pos: {
      lat: 35.6920154,
      lng: 139.7018685,
    },
    visitable: true,
    region: REGION.tokyo,
  },
  {
    name: '本店たん',
    storeName: 'ビックカメラ 池袋本店',
    url: 'honten',
    pos: {
      lat: 35.7315872,
      lng: 139.7129766,
    },
    visitable: true,
    region: REGION.tokyo,
  },
  {
    name: '立川たん',
    storeName: 'ビックカメラ 立川店',
    url: 'tachikawa',
    pos: {
      lat: 35.6993944,
      lng: 139.4145567,
    },
    visitable: true,
    region: REGION.tokyo,
  },
  {
    name: '天神2号たん',
    storeName: 'ビックカメラ 天神2号館',
    url: 'tenjin2',
    pos: {
      lat: 33.587547,
      lng: 130.398624,
    },
    visitable: true,
    region: REGION.misc,
  },
  {
    name: '所沢たん',
    storeName: 'ビックカメラ 所沢駅店',
    url: 'tokorozawa',
    pos: {
      lat: 35.7859589,
      lng: 139.4724948,
    },
    visitable: true,
    region: REGION.tokyo,
  },
  {
    name: 'プロスタたん',
    storeName: 'ビックフォトスタジオ 東京写真館',
    url: 'prpsta',
    pos: {
      lat: 35.7308323,
      lng: 139.7089542,
    },
    visitable: true,
    region: REGION.tokyo,
  },
  {
    name: '八尾たん',
    storeName: 'ビックカメラ アリオ八尾店',
    url: 'yao',
    pos: {
      lat: 34.6333375,
      lng: 135.6058441,
    },
    visitable: true,
    region: REGION.osaka,
  },
  {
    name: 'ふなとーたん',
    storeName: 'ビックカメラ 船橋東武店',
    url: 'funato',
    pos: {
      lat: 35.7020528,
      lng: 139.9850623,
    },
    visitable: false,
    region: REGION.tokyo,
  },
  {
    name: 'たまプラたん',
    storeName: 'ビックカメラ イトーヨーカドー たまプラーザ店',
    url: 'tamapla',
    pos: {
      lat: 35.5782694,
      lng: 139.5568821,
    },
    visitable: false,
    region: REGION.tokyo,
  },
  {
    name: '川崎たん',
    storeName: 'ビックカメラ ラゾーナ川崎店',
    url: 'kawasaki',
    pos: {
      lat: 35.5330257,
      lng: 139.6969505,
    },
    visitable: true,
    region: REGION.tokyo,
  },
  {
    name: '千葉たん',
    storeName: 'ビックカメラ 千葉駅前店',
    url: 'chiba',
    pos: {
      lat: 35.6117861,
      lng: 140.1155858,
    },
    visitable: true,
    region: REGION.tokyo,
  },
  {
    name: '天神1号たん',
    storeName: 'ビックカメラ 天神1号館',
    url: 'tenjin',
    pos: {
      lat: 33.5875219,
      lng: 130.4007108,
    },
    visitable: true,
    region: REGION.misc,
  },
  {
    name: '大宮たん',
    storeName: 'ビックカメラ 大宮西口そごう店',
    url: 'ohmiya',
    pos: {
      lat: 35.9044019,
      lng: 139.6209827,
    },
    visitable: true,
    region: REGION.tokyo,
  },
  {
    name: '鹿児島たん',
    storeName: 'ビックカメラ 鹿児島中央駅店',
    url: 'kagoshima',
    pos: {
      lat: 31.5838422,
      lng: 130.5406624,
    },
    visitable: true,
    region: REGION.misc,
  },
];

export { models, modelVersion };
